config/routes.rb
Rails.application.routes.draw do

  root :to => 'reserves#index'
  match 'reserves/:id/terms' => 'reserves#terms', :as => :reserve_terms, :via => :get
  match 'reserves/:id/clone' => 'reserves#clone', :as => :clone_reserve, :via => :get
  match 'reserves/add_item(.:format)' => 'reserves#add_item', :as => :add_reserves_item, :via => :get 
  match 'all_courses' => 'reserves#all_courses', :as => :all_courses, :via => :get 
  match 'all_courses_response' => 'reserves#all_courses_response', :as => :all_courses_response, :via => :get 
  
  resources :reserves
  
  

end

app/models/reserve.rb
class Reserve < ActiveRecord::Base
  before_save :process_sunet_ids

  has_and_belongs_to_many :editors

  # maybe turn these validations on during initial import?
  # validates :library, :presence => true # need to make sure (select library) isn't selected
  # validates :contact_name, :presence => true
  # validates :contact_phone, :presence => true
  # validates :contact_email, :presence => true

  serialize :item_list, type: Array, coder: YAML
  serialize :sent_item_list, type: Array, coder: YAML

  def course
    @course ||= CourseWorkCourses.new.find_by_compound_key(compound_key).first
  end

  def course_title
    course&.title || desc
  end

  def instructor_sunets
    return if self.instructor_sunet_ids.blank?

    self.instructor_sunet_ids.split(",").map(&:strip).compact_blank
  end

  def item_list
    (super || []).map do |item|
      cast_item_data(item)
    end
  end

  def sent_item_list
    (super || []).map do |item|
      cast_item_data(item)
    end
  end

  private

  def cast_item_data(item)
    item = item.to_unsafe_h if item.respond_to?(:to_unsafe_h)

    hash = {
      'media' => ActiveModel::Type::Boolean.new.cast(item['media']),
      'online' => ActiveModel::Type::Boolean.new.cast(item['online'])
    }

    item.merge(hash)
  end

  def process_sunet_ids
    editors = []

    if self.instructor_sunet_ids.present?
      self.instructor_sunet_ids.split(",").map(&:strip).compact_blank.each do |s|
        ed = Editor.find_or_create_by sunetid: s
        ed.save!
        editors << ed
      end
    end

    if self.editor_sunet_ids.present?
      self.editor_sunet_ids.split(",").map(&:strip).compact_blank.each do |s|
        ed = Editor.find_or_create_by sunetid: s
        ed.save!
        editors << ed
      end
    end

    self.editors = editors if editors.present?
  end
end

app/controllers/reserves_controller.rb
require 'net/http'
require 'nokogiri'
require 'terms'
class ReservesController < ApplicationController
  load_and_authorize_resource except: :new
  skip_authorize_resource only: :index
  skip_load_resource only: :index

  before_action :redirect_to_edit_when_reserve_exists, only: :new

  def index
    @reserves = if current_user.superuser?
                  Reserve.includes(:editors).where(editors: { sunetid: current_user.sunetid })
                else
                  Reserve.accessible_by(current_ability)
                end
  end

  def all_courses
    render layout: false if request.xhr?
  end

  def all_courses_response
    items = []
    if current_user.superuser?
      courses = CourseWorkCourses.new.all_courses
    else
      courses = CourseWorkCourses.new.find_by_sunet(current_user.sunetid)
    end
    courses.each do |course|
      cl = course.cross_listings.blank? ? "" : "(#{course.cross_listings})"
      items << [course.cid, "<a href='/reserves/new?comp_key=#{course.comp_key.gsub('&', '%26')}'>#{course.title}</a> #{cl}",
                course.instructor_names.join(", ")]
    end
    render json: { "aaData" => items }.to_json, layout: false
  end

  def show
    @reserve = Reserve.find(params[:id])
  end

  def new
    @course = course_for_compound_key(params[:comp_key])
    @reserve = Reserve.new(compound_key: params[:comp_key])
    raise RecordNotFound if @course.blank?

    authorize! :create, @reserve
  end

  def add_item
    respond_to do |format|
      format.js do
        if params[:sw] == 'false'
          @item = {}
        elsif params[:sw] == 'true'
          item = SearchWorksItem.new(params[:url])
          render(js: "alert('This does not appear to be a valid item in SearchWorks'); clean_up_loading();") && return unless item.valid?

          @item = item.to_h.with_indifferent_access
        end
      end
    end
  end

  def edit; end

  # Raising our own CanCan::AccessDenied here because we also let courses be created by the SUNet IDs in the course XML
  def create
    @reserve.save!

    send_course_reserve_request(@reserve) if params.key?(:send_request)
    redirect_to edit_reserve_path(@reserve[:id])
  end

  def update
    reserve = @reserve
    original_term = reserve.term
    if reserve_params[:term] != reserve.term && Reserve.where(compound_key: reserve.compound_key,
                                                              term: reserve_params[:term]).where.not(id: reserve.id).any?
      flash[:error] = "Course reserve list already exists for this course and term. The term has not been saved." # rubocop:disable Rails/I18nLocaleTexts
      reserve_params[:term] = original_term
    end
    reserve_params[:item_list] = [] unless reserve_params.key?(:item_list)
    reserve.update(reserve_params)
    send_course_reserve_request(@reserve) if params.key?(:send_request)

    redirect_to(controller: 'reserves', action: 'edit', id: params[:id])
  end

  def terms
    render layout: false if request.xhr?
  end

  def clone
    if Reserve.where(compound_key: @reserve.compound_key, term: params[:term]).any?
      flash[:error] = "Course reserve list already exists for this course and term." # rubocop:disable Rails/I18nLocaleTexts
      redirect_to(edit_reserve_path(@reserve)) && return
    end
    reserve = @reserve.dup
    reserve.has_been_sent = nil
    reserve.disabled = nil
    reserve.sent_date = nil
    reserve.term = params[:term]
    reserve.save!
    redirect_to(edit_reserve_path(reserve[:id]))
  end

  protected

  def course_for_compound_key(cid)
    CourseWorkCourses.new.find_by_compound_key(cid).first
  end

  def reserve_mail_address(reserve)
    if Settings.email.hardcoded_email_address
      Settings.email.hardcoded_email_address
    else
      "#{Settings.email_mapping[reserve.library]}, #{Settings.email.allforms}"
    end
  end

  def send_course_reserve_request(reserve)
    ReserveMailer.submit_request(reserve, reserve_mail_address(reserve), current_user).deliver_now.tap do
      reserve.update(reserve_params.merge(has_been_sent: true, sent_item_list: reserve_params[:item_list],
                                          sent_date: DateTime.now.strftime("%m-%d-%Y %I:%M%p").gsub("AM", "am").gsub("PM", "pm")))
    end
  end

  def reserve_params
    @reserve_params ||= begin
      reserve = params.require(:reserve).permit!
      reserve['item_list'] = reserve['item_list'].values if reserve['item_list']
      reserve
    end
  end

  def redirect_to_edit_when_reserve_exists
    reserve = Reserve.where(compound_key: params[:comp_key]).order("updated_at DESC").first
    return true if reserve.blank?

    redirect_to edit_reserve_path(reserve[:id])
  end
end

app/helpers/reserves_helper.rb
module ReservesHelper
end

app/views/reserves/_reserves_form.html.erb
<div id="course-details" class="d-block d-md-flex justify-content-between align-items-start">
	<div id="main-details">
	  <h1>Course Reserves List Request</h1>
	  <%- if params[:action] == "new" -%>
      <h2>
        <%= @course.cid if @course -%>: <%= @course.title if @course -%>
        <%= "(#{@course.cross_listings})" if @course and @course.cross_listings.present? %>
      </h2>
      <input type="hidden" name="reserve[cid]" value="<%= @course.cid if @course -%>" />
      <input type="hidden" name="reserve[sid]" value="<%= @course.sid if @course -%>" />
      <input type="hidden" name="reserve[desc]" value="<%= @course.title if @course -%>" />
      <input type="hidden" name="reserve[compound_key]" value="<%= @course.comp_key if @course -%>" />
      <input type="hidden" name="reserve[cross_listings]" value="<%= @course.cross_listings if @course -%>" />
      <div class="section mb-3"><span>Instructor:</span> <%= @course.instructor_names.join(', ') if @course -%></div>
      <input type="hidden" name="reserve[instructor_sunet_ids]" value="<%= @course.instructor_sunets.join(', ') if @course -%>" />
      <input type="hidden" name="reserve[instructor_names]" value="<%= @course.instructor_names.join(', ') if @course -%>" />
		<%- else -%>
  		<h2>
        <%= @reserve.cid if (@reserve and @reserve.cid) -%>: <%= @reserve.course_title if (@reserve and @reserve.course_title) -%>
  		  <%= "(#{@reserve.cross_listings})" if @reserve and @reserve.cross_listings and !@reserve.cross_listings.blank? %>
  		</h2>
  		<input type="hidden" name="reserve[cid]" value="<%= @reserve.cid if (@reserve and @reserve.cid) -%>" />
  		<input type="hidden" name="reserve[sid]" value="<%= @reserve.sid if (@reserve and @reserve.sid) -%>" />
  		<input type="hidden" name="reserve[compound_key]" value="<%= @reserve.compound_key if (@reserve and @reserve.compound_key) -%>" />
  		<input type="hidden" name="reserve[cross_listings]" value="<%= @reserve.cross_listings if (@reserve and @reserve.cross_listings) -%>" />
  		<div class="section mb-3"><span>Instructor:</span> <%= @reserve.instructor_names if (@reserve and @reserve.instructor_names) -%></div>
  		<input type="hidden" name="reserve[instructor_sunet_ids]" value="<%= @reserve.instructor_sunet_ids if (@reserve and @reserve.instructor_sunet_ids) -%>" />
  		<input type="hidden" name="reserve[instructor_names]" value="<%= @reserve.instructor_names if (@reserve and @reserve.instructor_names) -%>" />
		<%- end -%>

		<div class="section mb-3">
      Reserve for this quarter:
			<div id="reserve-timing" class="ms-4">
			  <%- if @reserve and @reserve.has_been_sent -%>
			    <%= @reserve.term %>
			  <%- else -%>
					<% Terms.all.each do |term| %>
						<div>
							<label class="<%= 'disabled' if has_existing_reserve_for_term?(@reserve, term) %>">
								<%= f.radio_button :term, term, disabled: has_existing_reserve_for_term?(@reserve, term) %>
								<%= render_term_label(term) %>
							</label>
						</div>
					<% end %>
  			<%- end -%>
			</div>
		</div>

    <% if @reserve.has_been_sent %>
      <div class="section mb-3">
        <div class="sent_date">Request sent <%= @reserve.sent_date %></div>

        <%= link_to('Copy this list for a new quarter', reserve_terms_path(@reserve), class: 'btn btn-secondary', data: { modal: 'trigger' }) %>
      </div>
    <% end %>

		<div class="section">
		  <label for="libraries" class="required mb-1">Send request to <span aria-hidden="true" class="badge text-bg-warning text-white">Required</span></label>
			<select id="libraries" name="reserve[library]" class="form-select ms-4" autocomplete="off">
				<option disabled selected hidden value="">(select library)</option>
				<% Settings.reserve_libraries.each do |code, library| %>
					<option value="<%= code -%>" <%= "selected='selected'" if @reserve.library.to_s == code.to_s -%> ><%= library -%></option>
				<% end %>
			</select>
		</div>
	</div>
	<fieldset id="list-management" class="card bg-light">
		<h3 class="card-header">List management</h3>
		<div class="card-body">
			<p>Who should the library contact about this list?</p>
			<div class="form-group row">
				<label for="contact_name" class="col-3 col-form-label" >Name</label>
			  <div class="col-9">
					<input class="form-control" name="reserve[contact_name]" value="<%= @reserve.contact_name if @reserve -%>" id="contact_name" type="text" />
				</div>
			</div>
			<div class="form-group row">
				<label for="contact_phone" class="col-3 col-form-label" >Phone</label>
				<div class="col-9">
				  <input class="form-control" name="reserve[contact_phone]"  value="<%= @reserve.contact_phone if @reserve -%>" id="contact_phone" type="tel"/>
				</div>
			</div>
			<div class="form-group row">
				<label for="contact_email" class="col-3 col-form-label" >Email</label>
				<div class="col-9">
				  <input class="form-control" name="reserve[contact_email]" value="<%= @reserve.contact_email if @reserve -%>"  id="contact_email" type="email"/>
				</div>
			</div>
				<label for="editor_sunet_ids" id="editors-list" class="col-form-label">Who can edit this list?</label>
				<div class="row mb-1 align-items-end">
					<div class="form-label col-3 text-right">
						<% ((params[:action] == "new" ? @course.instructor_sunets : @reserve.instructor_sunets) || []).each do |sunet| %>
							<span class="text-nowrap"><%= sunet %>,</span>
						<% end %>
					</div>
					<div class="col-9">
					 <input class="form-control" name="reserve[editor_sunet_ids]" value="<%= @reserve.editor_sunet_ids if @reserve -%>" id="editor_sunet_ids" type="text"/>
					</div>
				</div>
				<div class="form-text text-muted">(SUNet IDs, separated by commas)</div>
		</div>
	</fieldset>
</div>
<div id="item_list">
	<div class="header"></div>
	<% unless @reserve.blank? or @reserve.item_list.blank? %>
		<% @reserve.item_list.each_with_index do |item, index| %>
		  <%= render :partial => "reserves_item", :locals => { :item => item, :index => index }-%>
		<% end %>
	<% end %>
	<%- if !@reserve or !@reserve.disabled -%>
  	<div id="add_row" class="reserve d-flex">
  		<div class="enumerator last-row">
        <span class="counter"></span>
      </div>
      <div>
  			<label for="sw_url">Copy/paste an item URL or catkey from <%= link_to( "SearchWorks", "https://searchworks.stanford.edu/", rel: 'noopener', target: '_blank') %>.</label><br/>
				<div class="d-flex align-items-center mt-1">
					<div class="input-group w-auto">
						<input class="form-control" type="text" id="sw_url" />
            <%= link_to("add", { :controller => 'reserves', :action => 'add_item', :format => 'js', :sw => 'true' }, :remote => true, :class => "add-sw-item btn btn-secondary") -%>
					</div>
					<div>
            &nbsp; - or - <%= link_to("Reserve an item that's not in SearchWorks", { :controller => 'reserves', :action => 'add_item', :format => 'js', :sw => 'false' }, :id=>"add_custom", :remote => true ) %>
					</div>
				</div>
  		</div>
  	</div>
  <%- end -%>
</div>

app/views/reserves/_reserves_item.html.erb
<% uuid = SecureRandom.uuid %>
<%= fields_for "reserve[item_list][#{uuid}]", ReserveItem.new(item) do |f| %>
	<div class="reserve d-flex">
		<div class="enumerator"><span class="counter"></span></div>
		<div class="container">
			<div class="d-flex justify-content-between mb-2">
				<div class="">
					<% if item_in_searchworks?(item) %>
			      <p class="h5">
			        <%= link_to item['title'], "https://searchworks.stanford.edu/view/#{item['ckey']}", rel: 'noopener', target: '_blank' %>
			      </p>
			      <% if item['imprint'] %>
			        <p class="mb-1"><%= item['imprint'] %></p>
			      <% end %>
				    <% if item['online'] %>
				      <p class="mb-1"><span class="badge text-bg-success" aria-hidden="true">Online</span> Full text available online</p>
				    <% end %>
						<%= f.hidden_field :title %>
					<% else %>
						<%= f.label :title, 'Title', class: 'col-form-label mt-0' %>
						<%= f.text_area :title, cols: 60, rows: 3, class: 'form-control' %>
			  	<% end %>

					<%= f.hidden_field :imprint %>
					<%= f.hidden_field :ckey %>
					<%= f.hidden_field :media %>
					<%= f.hidden_field :online %>
				</div>
				<div class=""><%= link_to "[delete]", "", class: "delete", method: 'delete' -%></div>
			</div>
			<div>
				<hr />
				<div class="form-group d-flex flex-column flex-md-row mb-3 mb-sm-2">
					<div class="d-flex">
						<%= f.label :copies, 'Print copies needed:', class: 'col-form-label' %>
						<%= f.number_field :copies, class: 'form-control num_copies', max: 99 %>
					</div>

					<%= f.label :personal, class: 'col-form-label' do %>
						<%= f.check_box :personal %>

						The instructor will loan a copy to the library
					<% end %>
				</div>

				<div class="form-group d-flex mb-2">
					<%= f.label :loan_period, 'Loan period:', class: 'col-form-label' %>

					<% if ActiveModel::Type::Boolean.new.cast(item["media"]) %>
						<%= f.hidden_field :loan_period %>
					<% end %>

					<%= f.select :loan_period, Settings.loan_periods.to_h.values, {}, class: "loan-period form-select loan-select #{"media" if ActiveModel::Type::Boolean.new.cast(item["media"])}", disabled: ActiveModel::Type::Boolean.new.cast(item["media"]) %>
				</div>

				<div class="form-group d-flex flex-column flex-md-row mb-2">
					<%= content_tag :span, 'Is this a required or recommended text?', class: 'col-form-label pb-0'  %>
					<div class="d-flex flex-column mx-3">
						<%= f.label :required_true, class: 'col-form-label pt-0 pt-md-2 pb-0' do %>
							<%= f.radio_button :required, true %> Required
						<% end %>

						<%= f.label :required_false, class: 'col-form-label pt-0' do %>
							<%= f.radio_button :required, false %> Recommended
						<% end %>
					</div>
				</div>

				<% if item_in_searchworks?(item) %>
					<div class="form-group">
						<%= f.label :comment, 'Comments', class: 'col-form-label mt-0' %>
						<%= f.text_area :comment, cols: 60, rows: 3, class: 'form-control' %>
					</div>
				<% end %>
		  </div>
		</div>
	</div>
<% end %>

app/views/reserves/add_item.js.erb
$("#add_row").before("<%= escape_javascript(render(:partial => 'reserves_item', :locals => {:item => @item })) %>");
togglePartialWorkTextarea();
show_changed($("#item_list"));
check_validations();
check_loan_period();
$("#sw_url").val("");
clean_up_loading();

app/views/reserves/all_courses.html.erb
<div class="modal-header">
  <h1 class="modal-title h3">Select a course</h1>
  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
</div>

<div class="modal-body">
	<table id="all_courses" data-href="<%= all_courses_response_path %>" class="table">
		<thead class="bg-fog">
			<tr>
				<th id="course_id">Course ID</th>
				<th id="description">Description</th>
				<th id="instructor">Instructor</th>
			</tr>
		</thead>
		<tbody>

		</tbody>
	</table>
</div>
<script type="text/javascript">
  new DataTable("#all_courses", {
    processing: true,
    ajax: document.getElementById("all_courses").dataset.href,
    language: {
      emptyTable: "No courses found. You may not be authorized for any courses or the course list has not been released yet."
    }
  });
</script>

app/views/reserves/edit.html.erb
<div class="mb-5">
	<%= form_with model: @reserve, method: 'patch', html: { id: "reserve_form" } do |f| -%>
		<%= render :partial => "reserves_form", :locals => {:f => f} -%>
		<%- unless @reserve.disabled -%>
  		<input type="submit" id="save" value="Save draft" class="btn btn-secondary">
  		<%- if @reserve.has_been_sent -%>
  		  <input type="submit" name="send_request" value="Sent <%= @reserve.sent_date %>" class="btn btn-secondary" id="send" disabled>
  		<%- else -%>
    	  <input type="submit" name="send_request" value="Save and SEND request" class="btn btn-secondary" id="send" disabled>
    	<%- end -%>
    	<%= link_to "Cancel [discard changes]", root_url, class: 'btn btn-link' -%>
		<%- end -%>
	<%- end -%>
</div>
<%- # This will check validations on page load if the reserve hasn't been sent.  This is what allows us to keep sent items disabled when until the user changes something in the form.  -%>
<%- if !@reserve.has_been_sent or (@reserve.has_been_sent and @reserve.item_list != @reserve.sent_item_list) -%>
  <script type="text/javascript">
    check_validations();
  </script>
<%- end -%>

app/views/reserves/index.html.erb
<h1>Request Course Reserves</h1>
<div id="introduction">
  <p>
    Create or modify a list to place library materials (books, media, and licensed electronic resources)
    on reserve for your course. We can also circulate instructor-owned copies, and return materials
    to you at the end of the term.
  </p>

  <p>
    Please save and send your list at least 7 days before materials are needed for student use.
    If the library must purchase materials, it may take up to 6 weeks before they are available for students.
  </p>

  <p>
    <%= link_to 'https://library.stanford.edu/course-reserves', target: '_blank', rel: 'noopener' do %>
      More information about Course Reserves
    <% end %>
  </p>

  <h2>Questions?</h2>
  <p>
    Contact us at <%= mail_to Settings.email.questions %> or (650) 723-1492.
  </p>
</div>

<%= link_to "Create a new reserve list", all_courses_path, class: 'dialog btn btn-secondary my-3', data: { modal: 'trigger' }  -%>
<%- unless flash[:error].blank? -%>
  <div class="error"><%=  flash[:error] %></div>
<%- end -%>
<div id="reserves-section">
  <% unless @reserves.blank? %>
    <h2>Modify an existing reserve list</h2>
  	<table id="my-reserves" class="table table-striped">
  		<thead class="bg-fog">
  			<tr>
  				<th id="course_id" class="text-nowrap">Course ID</th>
  				<th id="term">Term</th>
  				<th id="actions" data-sort-method='none' class="no-sort">Actions</th>
  				<th id="course_description" data-sort-method='none' class="no-sort">Description</th>
  				<th id="instructor">Instructor</th>
  				<th id="status">Status</th>
  			</tr>
  		</thead>
  		<tbody>
  			<% @reserves.each do |course| -%>
  				<tr>
  					<td><%= course.cid -%></td>
  					<td data-sort='<%= sortable_term_value(course.term) %>'><%= course.term -%></td>
            <td class="text-nowrap">
              <%= link_to edit_reserve_path(course) do %>
                Edit <span class='visually-hidden'><%= "#{course.cid} - #{course.term}" %></span>
              <% end %>
              <%= link_to reserve_terms_path(course), class: 'copy-link dialog ms-4', data: { modal: 'trigger' } do %>
                Copy <span class='visually-hidden'><%= "#{course.cid} - #{course.term}" %>
              <% end if course.has_been_sent %>
            </td>
            <td><%= course.course_title -%></td>
            <td><%= course.instructor_names %></td>
            <td><%= (course.sent_date.blank? or course.sent_date.nil?) ? "Not sent" : "Sent #{course.sent_date}" %></td>
          </tr>
        <% end %>
      </tbody>


  	</table>
    <script>
      $(document).ready(function() {
        new DataTable("#my-reserves", {
          order: [
            [ 1, "desc" ]
          ],
          columns: [
            null,
            null,
            { "orderable": false },
            { "orderable": false },
            null,
            null
          ],
          info: false,
          paging: false,
          searching: false,
        });
      });
    </script>
  <% end %>
</div>

app/views/reserves/new.html.erb
<div>
	<%= form_for :reserve, :url =>  { :action => 'create'}, :html => {:id=>"reserve_form"} do |f| -%>
		<%= render :partial => "reserves_form", :locals => { :f => f } -%>
		<input type="submit" id="save" value="Save draft" class="btn btn-secondary">
    <input type="submit" name="send_request" value="Save and SEND request" class="btn btn-secondary" id="send" disabled>
    <%= link_to "Cancel [discard changes]", root_url, class: 'btn btn-link' -%>
	<%- end -%>
</div>

app/views/reserves/terms.html.erb
<div class="modal-header">
  <h1 class="modal-title h3"><%= @reserve.course_title %></h1>
  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
</div>

<div class="modal-body">
  <ul class='clone-reserve-list'>
    <% Terms.all.each do |term| %>
      <% next if term == @reserve.term %>
      <li>
        <% if has_existing_reserve_for_term?(@reserve, term) %>
          <%= term %> (reserve list already exists)
        <% else %>
          <%= link_to(term, clone_reserve_path(@reserve, term: term)) %>
        <% end %>
      </li>
    <% end %>
  </ul>
</div>